version: '2'
services:
  api:
    image: localhost:5000/docker-test
    build: .
    container_name: "docker-test"
    environment:
      - DOCKER_VARIABLE=testfromyaml
    volumes:
      - "./.env:/dockerTest/.env"
