name: IDH build workflow
# this is test commit
# reference link https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
on:
  push:
    # can use branches or branches-ignore to assign sequence of patterns matched against refs/heads
    branches:
      # - master           # Push events on master branch
      - developement     # Push events on developement branch
      # - 'mona/octocat' # Push events to branches matching refs/heads/mona/octocat
      # - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # can use tags or tags-ignore to assign sequence of patterns matched against refs/tags
    # tags:        
    #   - v1             # Push events to v1 tag
    #   - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
  pull_request:
    types: [ closed ]
    # Sequence of patterns matched against refs/heads
    branches:
      - master           # Push events on master branch
      # - developement     # Push events on developement branch
      # - 'mona/octocat' # Push events to branches matching refs/heads/mona/octocat
      # - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    # tags:        
    #   - v1             # Push events to v1 tag
    #   - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build-app:
    name: to build application include backend & frontend
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v1      
    - name: create ssh private key file and known_hosts
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
    - name: use ssh-agent to read ssh private key
      run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-add -l
    - name: checkout submodule
      run: |
          git submodule init
          git submodule update
    - name: npm install for backend and build
      run: |
          npm install
          npm run build
    # need to change check frontend repository path
    - name: checkout frontend repository
      env:
        FRONTEND_REPO_PATH: git@github.com:danielfeng7171/reactHello.git
      run: |
          cd app
          git clone "$FRONTEND_REPO_PATH" client
          cd client
    - name: npm install for frontend and build
      run: |
          npm install
          npm run build
          cd ../../
    - name: make master package
      run: npm i pkg && npx pkg . -o dist/pkg/intelligent-data-hub --options max_old_space_size=20000
    # upload to dropbox
    - name: upload executable to dropbox
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        BRANCH: ${{ github.ref }}
      run: |
        source checkmode.sh
        echo $MODE
        node uploadDropbox.js
    # - name: build docker cassandra image
    #   run: |
    #     sudo apt-get install curl
    #     source buildDockerImages.sh