# name: github action test

# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#     # To use this repository's private action, you must check out the repository
#     - name: Checkout
#       uses: actions/checkout@v1
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
#     # build docker image
#     #- name: Build the Docker image
#     #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#     - name: Build the docker image through docker-compose
#       run: docker-compose build
#     - name: start app
#       run: docker-compose up
name: IDH build workflow

on: [push]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    name: to build backend
    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.1.1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: check ssh key
      run: echo $SSH_AUTH_SOCK | export
    # To use this repository's private action, you must check out the repository
    # - name: checkout
    #   uses: actions/checkout@v1
    # - name: checkout submodule
    #   uses: textbook/git-checkout-submodule-action@master
    # - name: npm install
    #   run: npm install
    # - name: build backend
    #   run: npm run build