name: IDH test workflow

# reference link https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
on:
  pull_request:
    types: [ closed ]
    # Sequence of patterns matched against refs/heads
    branches:
      - master           # Push events on master branch
      - developement     # Push events on developement branch
      # - 'mona/octocat' # Push events to branches matching refs/heads/mona/octocat
      # - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    # tags:        
    #   - v1             # Push events to v1 tag
    #   - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  test-app:
    name: to test application
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v1      
    - name: npm install
      run: npm install
    - name: npm run test
      run: npm run test