name: IDH test workflow

# reference link https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
on: repository_dispatch
jobs:
  test-app:
    name: to test application
    runs-on: ubuntu-latest
    steps:
      - name: test client input
        run: |
          echo "field: ${{ github.event.client_payload.foo }}"
          echo "payload: ${{ toJson(github.event.client_payload) }}"
    # - name: checkout repository
    #   uses: actions/checkout@v1      
    # - name: npm install
    #   run: npm install
    # - name: npm run test
    #   run: npm run test
